# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NearestApi")

api.instance <- NearestApi$new()

test_that("Nearest", {
  # tests for Nearest
  # base path: https://eu1.locationiq.com/v1
  # Nearest Service
  # Snaps a coordinate to the street network and returns the nearest n matches. Where coordinates only supports a single {longitude},{latitude} entry.
  # @param character  coordinates  String of format {longitude},{latitude};{longitude},{latitude}[;{longitude},{latitude} ...] or polyline({polyline}) or polyline6({polyline6}). polyline follows Google's polyline format with precision 5 
  # @param character  generate.hints  Adds a Hint to the response which can be used in subsequent requests, see hints parameter. Input Value - true (default), false Format - Base64 String  (optional)
  # @param character  exclude  Additive list of classes to avoid, order does not matter. input Value - {class}[,{class}] Format - A class name determined by the profile or none.  (optional)
  # @param character  bearings  Limits the search to segments with given bearing in degrees towards true north in clockwise direction. List of positive integer pairs separated by semi-colon and bearings array should be equal to length of coordinate array. Input Value :- {bearing};{bearing}[;{bearing} ...] Bearing follows the following format : bearing {value},{range} integer 0 .. 360,integer 0 .. 180  (optional)
  # @param character  radiuses  Limits the search to given radius in meters Radiuses array length should be same as coordinates array, eaach value separated by semi-colon. Input Value - {radius};{radius}[;{radius} ...] Radius has following format :- double >= 0 or unlimited (default)  (optional)
  # @param character  approaches  Keep waypoints on curb side. Input Value - {approach};{approach}[;{approach} ...] Format - curb or unrestricted (default)  (optional)
  # @param integer  number  Number of nearest segments that should be returned. [ integer >= 1 (default 1) ]  (optional)
  # @return [DirectionsNearest]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

