# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Balance")

model.instance <- Balance$new()

test_that("status", {
  # tests for the property `status` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("balance", {
  # tests for the property `balance` (Daybalance)

  # uncomment below to test the property 
  #expect_equal(model.instance$`balance`, "EXPECTED_RESULT")
})

