# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DirectionsDirectionsRoutes")

model.instance <- DirectionsDirectionsRoutes$new()

test_that("legs", {
  # tests for the property `legs` (array[object])

  # uncomment below to test the property 
  #expect_equal(model.instance$`legs`, "EXPECTED_RESULT")
})

test_that("weight_name", {
  # tests for the property `weight_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`weight_name`, "EXPECTED_RESULT")
})

test_that("geometry", {
  # tests for the property `geometry` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`geometry`, "EXPECTED_RESULT")
})

test_that("weight", {
  # tests for the property `weight` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`weight`, "EXPECTED_RESULT")
})

test_that("distance", {
  # tests for the property `distance` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`distance`, "EXPECTED_RESULT")
})

test_that("duration", {
  # tests for the property `duration` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`duration`, "EXPECTED_RESULT")
})

