# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DirectionsDirections")

model.instance <- DirectionsDirections$new()

test_that("code", {
  # tests for the property `code` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

test_that("waypoints", {
  # tests for the property `waypoints` (array[object])

  # uncomment below to test the property 
  #expect_equal(model.instance$`waypoints`, "EXPECTED_RESULT")
})

test_that("routes", {
  # tests for the property `routes` (array[DirectionsDirectionsRoutes])

  # uncomment below to test the property 
  #expect_equal(model.instance$`routes`, "EXPECTED_RESULT")
})

