# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Address")

model.instance <- Address$new()

test_that("house_number", {
  # tests for the property `house_number` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`house_number`, "EXPECTED_RESULT")
})

test_that("road", {
  # tests for the property `road` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`road`, "EXPECTED_RESULT")
})

test_that("residential", {
  # tests for the property `residential` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`residential`, "EXPECTED_RESULT")
})

test_that("borough", {
  # tests for the property `borough` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`borough`, "EXPECTED_RESULT")
})

test_that("neighbourhood", {
  # tests for the property `neighbourhood` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`neighbourhood`, "EXPECTED_RESULT")
})

test_that("quarter", {
  # tests for the property `quarter` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`quarter`, "EXPECTED_RESULT")
})

test_that("hamlet", {
  # tests for the property `hamlet` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`hamlet`, "EXPECTED_RESULT")
})

test_that("suburb", {
  # tests for the property `suburb` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`suburb`, "EXPECTED_RESULT")
})

test_that("island", {
  # tests for the property `island` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`island`, "EXPECTED_RESULT")
})

test_that("village", {
  # tests for the property `village` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`village`, "EXPECTED_RESULT")
})

test_that("town", {
  # tests for the property `town` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`town`, "EXPECTED_RESULT")
})

test_that("city", {
  # tests for the property `city` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`city`, "EXPECTED_RESULT")
})

test_that("city_district", {
  # tests for the property `city_district` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`city_district`, "EXPECTED_RESULT")
})

test_that("county", {
  # tests for the property `county` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`county`, "EXPECTED_RESULT")
})

test_that("state", {
  # tests for the property `state` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`state`, "EXPECTED_RESULT")
})

test_that("state_district", {
  # tests for the property `state_district` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`state_district`, "EXPECTED_RESULT")
})

test_that("postcode", {
  # tests for the property `postcode` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`postcode`, "EXPECTED_RESULT")
})

test_that("country", {
  # tests for the property `country` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`country`, "EXPECTED_RESULT")
})

test_that("country_code", {
  # tests for the property `country_code` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`country_code`, "EXPECTED_RESULT")
})

test_that("state_code", {
  # tests for the property `state_code` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`state_code`, "EXPECTED_RESULT")
})

