# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Matchquality")

model.instance <- Matchquality$new()

test_that("matchcode", {
  # tests for the property `matchcode` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`matchcode`, "EXPECTED_RESULT")
})

test_that("matchtype", {
  # tests for the property `matchtype` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`matchtype`, "EXPECTED_RESULT")
})

test_that("matchlevel", {
  # tests for the property `matchlevel` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`matchlevel`, "EXPECTED_RESULT")
})

