# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Daybalance")

model.instance <- Daybalance$new()

test_that("day", {
  # tests for the property `day` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`day`, "EXPECTED_RESULT")
})

test_that("bonus", {
  # tests for the property `bonus` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`bonus`, "EXPECTED_RESULT")
})

