# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DirectionsApi")

api.instance <- DirectionsApi$new()

test_that("Directions", {
  # tests for Directions
  # base path: https://eu1.locationiq.com/v1
  # Directions Service
  # Finds the fastest route between coordinates in the supplied order.
  # @param character  coordinates  String of format {longitude},{latitude};{longitude},{latitude}[;{longitude},{latitude} ...] or polyline({polyline}) or polyline6({polyline6}). polyline follows Google's polyline format with precision 5 
  # @param character  bearings  Limits the search to segments with given bearing in degrees towards true north in clockwise direction. List of positive integer pairs separated by semi-colon and bearings array should be equal to length of coordinate array. Input Value :- {bearing};{bearing}[;{bearing} ...] Bearing follows the following format : bearing {value},{range} integer 0 .. 360,integer 0 .. 180  (optional)
  # @param character  radiuses  Limits the search to given radius in meters Radiuses array length should be same as coordinates array, eaach value separated by semi-colon. Input Value - {radius};{radius}[;{radius} ...] Radius has following format :- double >= 0 or unlimited (default)  (optional)
  # @param character  generate.hints  Adds a Hint to the response which can be used in subsequent requests, see hints parameter. Input Value - true (default), false Format - Base64 String  (optional)
  # @param character  approaches  Keep waypoints on curb side. Input Value - {approach};{approach}[;{approach} ...] Format - curb or unrestricted (default)  (optional)
  # @param character  exclude  Additive list of classes to avoid, order does not matter. input Value - {class}[,{class}] Format - A class name determined by the profile or none.  (optional)
  # @param numeric  alternatives  Search for alternative routes. Passing a number alternatives=n searches for up to n alternative routes. [ true, false (default), or Number ]  (optional)
  # @param character  steps  Returned route steps for each route leg [ true, false (default) ]  (optional)
  # @param character  annotations  Returns additional metadata for each coordinate along the route geometry.  [ true, false (default), nodes, distance, duration, datasources, weight, speed ]  (optional)
  # @param character  geometries  Returned route geometry format (influences overview and per step) [ polyline (default), polyline6, geojson ]  (optional)
  # @param character  overview  Add overview geometry either full, simplified according to highest zoom level it could be display on, or not at all. [ simplified (default), full, false ]  (optional)
  # @param character  continue.straight  Forces the route to keep going straight at waypoints constraining uturns there even if it would be faster. Default value depends on the profile [ default (default), true, false ]  (optional)
  # @return [DirectionsDirections]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

