# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Location")

model.instance <- Location$new()

test_that("distance", {
  # tests for the property `distance` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`distance`, "EXPECTED_RESULT")
})

test_that("place_id", {
  # tests for the property `place_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`place_id`, "EXPECTED_RESULT")
})

test_that("licence", {
  # tests for the property `licence` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`licence`, "EXPECTED_RESULT")
})

test_that("osm_type", {
  # tests for the property `osm_type` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`osm_type`, "EXPECTED_RESULT")
})

test_that("osm_id", {
  # tests for the property `osm_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`osm_id`, "EXPECTED_RESULT")
})

test_that("boundingbox", {
  # tests for the property `boundingbox` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`boundingbox`, "EXPECTED_RESULT")
})

test_that("lat", {
  # tests for the property `lat` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`lat`, "EXPECTED_RESULT")
})

test_that("lon", {
  # tests for the property `lon` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`lon`, "EXPECTED_RESULT")
})

test_that("display_name", {
  # tests for the property `display_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`display_name`, "EXPECTED_RESULT")
})

test_that("class", {
  # tests for the property `class` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`class`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("importance", {
  # tests for the property `importance` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`importance`, "EXPECTED_RESULT")
})

test_that("address", {
  # tests for the property `address` (Address)

  # uncomment below to test the property 
  #expect_equal(model.instance$`address`, "EXPECTED_RESULT")
})

test_that("namedetails", {
  # tests for the property `namedetails` (Namedetails)

  # uncomment below to test the property 
  #expect_equal(model.instance$`namedetails`, "EXPECTED_RESULT")
})

test_that("matchquality", {
  # tests for the property `matchquality` (Matchquality)

  # uncomment below to test the property 
  #expect_equal(model.instance$`matchquality`, "EXPECTED_RESULT")
})

