# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DirectionsMatching")

model.instance <- DirectionsMatching$new()

test_that("code", {
  # tests for the property `code` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

test_that("tracepoints", {
  # tests for the property `tracepoints` (array[object])

  # uncomment below to test the property 
  #expect_equal(model.instance$`tracepoints`, "EXPECTED_RESULT")
})

test_that("matchings", {
  # tests for the property `matchings` (array[object])

  # uncomment below to test the property 
  #expect_equal(model.instance$`matchings`, "EXPECTED_RESULT")
})

