# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DirectionsNearestWaypoints")

model.instance <- DirectionsNearestWaypoints$new()

test_that("nodes", {
  # tests for the property `nodes` (array[numeric])

  # uncomment below to test the property 
  #expect_equal(model.instance$`nodes`, "EXPECTED_RESULT")
})

test_that("distance", {
  # tests for the property `distance` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`distance`, "EXPECTED_RESULT")
})

test_that("location", {
  # tests for the property `location` (array[numeric])

  # uncomment below to test the property 
  #expect_equal(model.instance$`location`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

