# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DirectionsNearest")

model.instance <- DirectionsNearest$new()

test_that("code", {
  # tests for the property `code` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

test_that("waypoints", {
  # tests for the property `waypoints` (array[DirectionsNearestWaypoints])

  # uncomment below to test the property 
  #expect_equal(model.instance$`waypoints`, "EXPECTED_RESULT")
})

