# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BalanceApi")

api.instance <- BalanceApi$new()

test_that("Balance", {
  # tests for Balance
  # base path: https://eu1.locationiq.com/v1
  # The Balance API provides a count of request credits left in the user&#39;s account for the day. Balance is reset at midnight UTC everyday (00:00 UTC).
  # @return [Balance]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

