# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MatchingApi")

api.instance <- MatchingApi$new()

test_that("Matching", {
  # tests for Matching
  # base path: https://eu1.locationiq.com/v1
  # Matching Service
  # Matching API matches or snaps given GPS points to the road network in the most plausible way.  Please note the request might result multiple sub-traces.  Large jumps in the timestamps (&gt; 60s) or improbable transitions lead to trace splits if a complete matching could not be found. The algorithm might not be able to match all points. Outliers are removed if they can not be matched successfully.
  # @param character  coordinates  String of format {longitude},{latitude};{longitude},{latitude}[;{longitude},{latitude} ...] or polyline({polyline}) or polyline6({polyline6}). polyline follows Google's polyline format with precision 5 
  # @param character  generate.hints  Adds a Hint to the response which can be used in subsequent requests, see hints parameter. Input Value - true (default), false Format - Base64 String  (optional)
  # @param character  approaches  Keep waypoints on curb side. Input Value - {approach};{approach}[;{approach} ...] Format - curb or unrestricted (default)  (optional)
  # @param character  exclude  Additive list of classes to avoid, order does not matter. input Value - {class}[,{class}] Format - A class name determined by the profile or none.  (optional)
  # @param character  bearings  Limits the search to segments with given bearing in degrees towards true north in clockwise direction. List of positive integer pairs separated by semi-colon and bearings array should be equal to length of coordinate array. Input Value :- {bearing};{bearing}[;{bearing} ...] Bearing follows the following format : bearing {value},{range} integer 0 .. 360,integer 0 .. 180  (optional)
  # @param character  radiuses  Limits the search to given radius in meters Radiuses array length should be same as coordinates array, eaach value separated by semi-colon. Input Value - {radius};{radius}[;{radius} ...] Radius has following format :- double >= 0 or unlimited (default)  (optional)
  # @param character  steps  Returned route steps for each route leg [ true, false (default) ]  (optional)
  # @param character  annotations  Returns additional metadata for each coordinate along the route geometry.  [ true, false (default), nodes, distance, duration, datasources, weight, speed ]  (optional)
  # @param character  geometries  Returned route geometry format (influences overview and per step) [ polyline (default), polyline6, geojson ]  (optional)
  # @param character  overview  Add overview geometry either full, simplified according to highest zoom level it could be display on, or not at all. [ simplified (default), full, false ]  (optional)
  # @param character  timestamps  Timestamps for the input locations in seconds since UNIX epoch. Timestamps need to be monotonically increasing. [ {timestamp};{timestamp}[;{timestamp} ...]  integer seconds since UNIX epoch  (optional)
  # @param character  gaps  Allows the input track splitting based on huge timestamp gaps between points. [ split (default), ignore ]  (optional)
  # @param character  tidy  Allows the input track modification to obtain better matching quality for noisy tracks. [ true, false (default) ]  (optional)
  # @param character  waypoints  Treats input coordinates indicated by given indices as waypoints in returned Match object. Default is to treat all input coordinates as waypoints. [ {index};{index};{index}... ]  (optional)
  # @return [DirectionsMatching]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

