# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DirectionsMatrix")

model.instance <- DirectionsMatrix$new()

test_that("code", {
  # tests for the property `code` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

test_that("distances", {
  # tests for the property `distances` (array[numeric])

  # uncomment below to test the property 
  #expect_equal(model.instance$`distances`, "EXPECTED_RESULT")
})

test_that("fallback_speed_cells", {
  # tests for the property `fallback_speed_cells` (array[numeric])

  # uncomment below to test the property 
  #expect_equal(model.instance$`fallback_speed_cells`, "EXPECTED_RESULT")
})

test_that("sources", {
  # tests for the property `sources` (array[DirectionsMatrixSources])

  # uncomment below to test the property 
  #expect_equal(model.instance$`sources`, "EXPECTED_RESULT")
})

test_that("destinations", {
  # tests for the property `destinations` (array[DirectionsMatrixSources])

  # uncomment below to test the property 
  #expect_equal(model.instance$`destinations`, "EXPECTED_RESULT")
})

