# LocationIQ
#
# LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
#
# OpenAPI spec version: 1.0.1
# 
# Generated by: https://openapi-generator.tech


#' Address Class
#'
#' @field house_number 
#' @field road 
#' @field residential 
#' @field village 
#' @field county 
#' @field state 
#' @field postcode 
#' @field country 
#' @field country_code 
#' @field city 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Address <- R6::R6Class(
  'Address',
  public = list(
    `house_number` = NULL,
    `road` = NULL,
    `residential` = NULL,
    `village` = NULL,
    `county` = NULL,
    `state` = NULL,
    `postcode` = NULL,
    `country` = NULL,
    `country_code` = NULL,
    `city` = NULL,
    initialize = function(`house_number`, `road`, `residential`, `village`, `county`, `state`, `postcode`, `country`, `country_code`, `city`){
      if (!missing(`house_number`)) {
        stopifnot(is.character(`house_number`), length(`house_number`) == 1)
        self$`house_number` <- `house_number`
      }
      if (!missing(`road`)) {
        stopifnot(is.character(`road`), length(`road`) == 1)
        self$`road` <- `road`
      }
      if (!missing(`residential`)) {
        stopifnot(is.character(`residential`), length(`residential`) == 1)
        self$`residential` <- `residential`
      }
      if (!missing(`village`)) {
        stopifnot(is.character(`village`), length(`village`) == 1)
        self$`village` <- `village`
      }
      if (!missing(`county`)) {
        stopifnot(is.character(`county`), length(`county`) == 1)
        self$`county` <- `county`
      }
      if (!missing(`state`)) {
        stopifnot(is.character(`state`), length(`state`) == 1)
        self$`state` <- `state`
      }
      if (!missing(`postcode`)) {
        stopifnot(is.character(`postcode`), length(`postcode`) == 1)
        self$`postcode` <- `postcode`
      }
      if (!missing(`country`)) {
        stopifnot(is.character(`country`), length(`country`) == 1)
        self$`country` <- `country`
      }
      if (!missing(`country_code`)) {
        stopifnot(is.character(`country_code`), length(`country_code`) == 1)
        self$`country_code` <- `country_code`
      }
      if (!missing(`city`)) {
        stopifnot(is.character(`city`), length(`city`) == 1)
        self$`city` <- `city`
      }
    },
    toJSON = function() {
      AddressObject <- list()
      if (!is.null(self$`house_number`)) {
        AddressObject[['house_number']] <- self$`house_number`
      }
      if (!is.null(self$`road`)) {
        AddressObject[['road']] <- self$`road`
      }
      if (!is.null(self$`residential`)) {
        AddressObject[['residential']] <- self$`residential`
      }
      if (!is.null(self$`village`)) {
        AddressObject[['village']] <- self$`village`
      }
      if (!is.null(self$`county`)) {
        AddressObject[['county']] <- self$`county`
      }
      if (!is.null(self$`state`)) {
        AddressObject[['state']] <- self$`state`
      }
      if (!is.null(self$`postcode`)) {
        AddressObject[['postcode']] <- self$`postcode`
      }
      if (!is.null(self$`country`)) {
        AddressObject[['country']] <- self$`country`
      }
      if (!is.null(self$`country_code`)) {
        AddressObject[['country_code']] <- self$`country_code`
      }
      if (!is.null(self$`city`)) {
        AddressObject[['city']] <- self$`city`
      }

      AddressObject
    },
    fromJSON = function(AddressJson) {
      AddressObject <- jsonlite::fromJSON(AddressJson)
      if (!is.null(AddressObject$`house_number`)) {
        self$`house_number` <- AddressObject$`house_number`
      }
      if (!is.null(AddressObject$`road`)) {
        self$`road` <- AddressObject$`road`
      }
      if (!is.null(AddressObject$`residential`)) {
        self$`residential` <- AddressObject$`residential`
      }
      if (!is.null(AddressObject$`village`)) {
        self$`village` <- AddressObject$`village`
      }
      if (!is.null(AddressObject$`county`)) {
        self$`county` <- AddressObject$`county`
      }
      if (!is.null(AddressObject$`state`)) {
        self$`state` <- AddressObject$`state`
      }
      if (!is.null(AddressObject$`postcode`)) {
        self$`postcode` <- AddressObject$`postcode`
      }
      if (!is.null(AddressObject$`country`)) {
        self$`country` <- AddressObject$`country`
      }
      if (!is.null(AddressObject$`country_code`)) {
        self$`country_code` <- AddressObject$`country_code`
      }
      if (!is.null(AddressObject$`city`)) {
        self$`city` <- AddressObject$`city`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "house_number": %s,
           "road": %s,
           "residential": %s,
           "village": %s,
           "county": %s,
           "state": %s,
           "postcode": %s,
           "country": %s,
           "country_code": %s,
           "city": %s
        }',
        self$`house_number`,
        self$`road`,
        self$`residential`,
        self$`village`,
        self$`county`,
        self$`state`,
        self$`postcode`,
        self$`country`,
        self$`country_code`,
        self$`city`
      )
    },
    fromJSONString = function(AddressJson) {
      AddressObject <- jsonlite::fromJSON(AddressJson)
      self$`house_number` <- AddressObject$`house_number`
      self$`road` <- AddressObject$`road`
      self$`residential` <- AddressObject$`residential`
      self$`village` <- AddressObject$`village`
      self$`county` <- AddressObject$`county`
      self$`state` <- AddressObject$`state`
      self$`postcode` <- AddressObject$`postcode`
      self$`country` <- AddressObject$`country`
      self$`country_code` <- AddressObject$`country_code`
      self$`city` <- AddressObject$`city`
    }
  )
)
