# LocationIQ
#
# LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
#
# OpenAPI spec version: 1.0.1
# 
# Generated by: https://openapi-generator.tech


#' Balance Class
#'
#' @field status 
#' @field balance 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Balance <- R6::R6Class(
  'Balance',
  public = list(
    `status` = NULL,
    `balance` = NULL,
    initialize = function(`status`, `balance`){
      if (!missing(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!missing(`balance`)) {
        stopifnot(R6::is.R6(`balance`))
        self$`balance` <- `balance`
      }
    },
    toJSON = function() {
      BalanceObject <- list()
      if (!is.null(self$`status`)) {
        BalanceObject[['status']] <- self$`status`
      }
      if (!is.null(self$`balance`)) {
        BalanceObject[['balance']] <- self$`balance`$toJSON()
      }

      BalanceObject
    },
    fromJSON = function(BalanceJson) {
      BalanceObject <- jsonlite::fromJSON(BalanceJson)
      if (!is.null(BalanceObject$`status`)) {
        self$`status` <- BalanceObject$`status`
      }
      if (!is.null(BalanceObject$`balance`)) {
        balanceObject <- Daybalance$new()
        balanceObject$fromJSON(jsonlite::toJSON(BalanceObject$balance, auto_unbox = TRUE))
        self$`balance` <- balanceObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "status": %s,
           "balance": %s
        }',
        self$`status`,
        self$`balance`$toJSON()
      )
    },
    fromJSONString = function(BalanceJson) {
      BalanceObject <- jsonlite::fromJSON(BalanceJson)
      self$`status` <- BalanceObject$`status`
      DaybalanceObject <- Daybalance$new()
      self$`balance` <- DaybalanceObject$fromJSON(jsonlite::toJSON(BalanceObject$balance, auto_unbox = TRUE))
    }
  )
)
