# LocationIQ
#
# LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
#
# The version of the OpenAPI document: 1.1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Daybalance
#' @description Daybalance Class
#' @format An \code{R6Class} generator object
#' @field day  integer [optional]
#'
#' @field bonus  integer [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Daybalance <- R6::R6Class(
  'Daybalance',
  public = list(
    `day` = NULL,
    `bonus` = NULL,
    initialize = function(`day`=NULL, `bonus`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`day`)) {
        stopifnot(is.numeric(`day`), length(`day`) == 1)
        self$`day` <- `day`
      }
      if (!is.null(`bonus`)) {
        stopifnot(is.numeric(`bonus`), length(`bonus`) == 1)
        self$`bonus` <- `bonus`
      }
    },
    toJSON = function() {
      DaybalanceObject <- list()
      if (!is.null(self$`day`)) {
        DaybalanceObject[['day']] <-
          self$`day`
      }
      if (!is.null(self$`bonus`)) {
        DaybalanceObject[['bonus']] <-
          self$`bonus`
      }

      DaybalanceObject
    },
    fromJSON = function(DaybalanceJson) {
      DaybalanceObject <- jsonlite::fromJSON(DaybalanceJson)
      if (!is.null(DaybalanceObject$`day`)) {
        self$`day` <- DaybalanceObject$`day`
      }
      if (!is.null(DaybalanceObject$`bonus`)) {
        self$`bonus` <- DaybalanceObject$`bonus`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`day`)) {
        sprintf(
        '"day":
          %d
                ',
        self$`day`
        )},
        if (!is.null(self$`bonus`)) {
        sprintf(
        '"bonus":
          %d
                ',
        self$`bonus`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DaybalanceJson) {
      DaybalanceObject <- jsonlite::fromJSON(DaybalanceJson)
      self$`day` <- DaybalanceObject$`day`
      self$`bonus` <- DaybalanceObject$`bonus`
      self
    }
  )
)
