# LocationIQ
#
# LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
#
# The version of the OpenAPI document: 1.1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DirectionsNearestWaypoints
#' @description DirectionsNearestWaypoints Class
#' @format An \code{R6Class} generator object
#' @field nodes  list( numeric ) [optional]
#'
#' @field distance  numeric [optional]
#'
#' @field location  list( numeric ) [optional]
#'
#' @field name  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DirectionsNearestWaypoints <- R6::R6Class(
  'DirectionsNearestWaypoints',
  public = list(
    `nodes` = NULL,
    `distance` = NULL,
    `location` = NULL,
    `name` = NULL,
    initialize = function(`nodes`=NULL, `distance`=NULL, `location`=NULL, `name`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`nodes`)) {
        stopifnot(is.vector(`nodes`), length(`nodes`) != 0)
        sapply(`nodes`, function(x) stopifnot(is.character(x)))
        self$`nodes` <- `nodes`
      }
      if (!is.null(`distance`)) {
        self$`distance` <- `distance`
      }
      if (!is.null(`location`)) {
        stopifnot(is.vector(`location`), length(`location`) != 0)
        sapply(`location`, function(x) stopifnot(is.character(x)))
        self$`location` <- `location`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      DirectionsNearestWaypointsObject <- list()
      if (!is.null(self$`nodes`)) {
        DirectionsNearestWaypointsObject[['nodes']] <-
          self$`nodes`
      }
      if (!is.null(self$`distance`)) {
        DirectionsNearestWaypointsObject[['distance']] <-
          self$`distance`
      }
      if (!is.null(self$`location`)) {
        DirectionsNearestWaypointsObject[['location']] <-
          self$`location`
      }
      if (!is.null(self$`name`)) {
        DirectionsNearestWaypointsObject[['name']] <-
          self$`name`
      }

      DirectionsNearestWaypointsObject
    },
    fromJSON = function(DirectionsNearestWaypointsJson) {
      DirectionsNearestWaypointsObject <- jsonlite::fromJSON(DirectionsNearestWaypointsJson)
      if (!is.null(DirectionsNearestWaypointsObject$`nodes`)) {
        self$`nodes` <- ApiClient$new()$deserializeObj(DirectionsNearestWaypointsObject$`nodes`, "array[numeric]", loadNamespace("locationiq"))
      }
      if (!is.null(DirectionsNearestWaypointsObject$`distance`)) {
        self$`distance` <- DirectionsNearestWaypointsObject$`distance`
      }
      if (!is.null(DirectionsNearestWaypointsObject$`location`)) {
        self$`location` <- ApiClient$new()$deserializeObj(DirectionsNearestWaypointsObject$`location`, "array[numeric]", loadNamespace("locationiq"))
      }
      if (!is.null(DirectionsNearestWaypointsObject$`name`)) {
        self$`name` <- DirectionsNearestWaypointsObject$`name`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`nodes`)) {
        sprintf(
        '"nodes":
           [%s]
        ',
        paste(unlist(lapply(self$`nodes`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`distance`)) {
        sprintf(
        '"distance":
          %d
                ',
        self$`distance`
        )},
        if (!is.null(self$`location`)) {
        sprintf(
        '"location":
           [%s]
        ',
        paste(unlist(lapply(self$`location`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DirectionsNearestWaypointsJson) {
      DirectionsNearestWaypointsObject <- jsonlite::fromJSON(DirectionsNearestWaypointsJson)
      self$`nodes` <- ApiClient$new()$deserializeObj(DirectionsNearestWaypointsObject$`nodes`, "array[numeric]", loadNamespace("locationiq"))
      self$`distance` <- DirectionsNearestWaypointsObject$`distance`
      self$`location` <- ApiClient$new()$deserializeObj(DirectionsNearestWaypointsObject$`location`, "array[numeric]", loadNamespace("locationiq"))
      self$`name` <- DirectionsNearestWaypointsObject$`name`
      self
    }
  )
)
