# LocationIQ
#
# LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
#
# The version of the OpenAPI document: 1.1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DirectionsDirectionsRoutes
#' @description DirectionsDirectionsRoutes Class
#' @format An \code{R6Class} generator object
#' @field legs  list( object ) [optional]
#'
#' @field weight_name  character [optional]
#'
#' @field geometry  character [optional]
#'
#' @field weight  numeric [optional]
#'
#' @field distance  numeric [optional]
#'
#' @field duration  numeric [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DirectionsDirectionsRoutes <- R6::R6Class(
  'DirectionsDirectionsRoutes',
  public = list(
    `legs` = NULL,
    `weight_name` = NULL,
    `geometry` = NULL,
    `weight` = NULL,
    `distance` = NULL,
    `duration` = NULL,
    initialize = function(`legs`=NULL, `weight_name`=NULL, `geometry`=NULL, `weight`=NULL, `distance`=NULL, `duration`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`legs`)) {
        stopifnot(is.vector(`legs`), length(`legs`) != 0)
        sapply(`legs`, function(x) stopifnot(is.character(x)))
        self$`legs` <- `legs`
      }
      if (!is.null(`weight_name`)) {
        stopifnot(is.character(`weight_name`), length(`weight_name`) == 1)
        self$`weight_name` <- `weight_name`
      }
      if (!is.null(`geometry`)) {
        stopifnot(is.character(`geometry`), length(`geometry`) == 1)
        self$`geometry` <- `geometry`
      }
      if (!is.null(`weight`)) {
        self$`weight` <- `weight`
      }
      if (!is.null(`distance`)) {
        self$`distance` <- `distance`
      }
      if (!is.null(`duration`)) {
        self$`duration` <- `duration`
      }
    },
    toJSON = function() {
      DirectionsDirectionsRoutesObject <- list()
      if (!is.null(self$`legs`)) {
        DirectionsDirectionsRoutesObject[['legs']] <-
          self$`legs`
      }
      if (!is.null(self$`weight_name`)) {
        DirectionsDirectionsRoutesObject[['weight_name']] <-
          self$`weight_name`
      }
      if (!is.null(self$`geometry`)) {
        DirectionsDirectionsRoutesObject[['geometry']] <-
          self$`geometry`
      }
      if (!is.null(self$`weight`)) {
        DirectionsDirectionsRoutesObject[['weight']] <-
          self$`weight`
      }
      if (!is.null(self$`distance`)) {
        DirectionsDirectionsRoutesObject[['distance']] <-
          self$`distance`
      }
      if (!is.null(self$`duration`)) {
        DirectionsDirectionsRoutesObject[['duration']] <-
          self$`duration`
      }

      DirectionsDirectionsRoutesObject
    },
    fromJSON = function(DirectionsDirectionsRoutesJson) {
      DirectionsDirectionsRoutesObject <- jsonlite::fromJSON(DirectionsDirectionsRoutesJson)
      if (!is.null(DirectionsDirectionsRoutesObject$`legs`)) {
        self$`legs` <- ApiClient$new()$deserializeObj(DirectionsDirectionsRoutesObject$`legs`, "array[object]", loadNamespace("openapi"))
      }
      if (!is.null(DirectionsDirectionsRoutesObject$`weight_name`)) {
        self$`weight_name` <- DirectionsDirectionsRoutesObject$`weight_name`
      }
      if (!is.null(DirectionsDirectionsRoutesObject$`geometry`)) {
        self$`geometry` <- DirectionsDirectionsRoutesObject$`geometry`
      }
      if (!is.null(DirectionsDirectionsRoutesObject$`weight`)) {
        self$`weight` <- DirectionsDirectionsRoutesObject$`weight`
      }
      if (!is.null(DirectionsDirectionsRoutesObject$`distance`)) {
        self$`distance` <- DirectionsDirectionsRoutesObject$`distance`
      }
      if (!is.null(DirectionsDirectionsRoutesObject$`duration`)) {
        self$`duration` <- DirectionsDirectionsRoutesObject$`duration`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`legs`)) {
        sprintf(
        '"legs":
           [%s]
        ',
        paste(unlist(lapply(self$`legs`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`weight_name`)) {
        sprintf(
        '"weight_name":
          "%s"
                ',
        self$`weight_name`
        )},
        if (!is.null(self$`geometry`)) {
        sprintf(
        '"geometry":
          "%s"
                ',
        self$`geometry`
        )},
        if (!is.null(self$`weight`)) {
        sprintf(
        '"weight":
          %d
                ',
        self$`weight`
        )},
        if (!is.null(self$`distance`)) {
        sprintf(
        '"distance":
          %d
                ',
        self$`distance`
        )},
        if (!is.null(self$`duration`)) {
        sprintf(
        '"duration":
          %d
                ',
        self$`duration`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DirectionsDirectionsRoutesJson) {
      DirectionsDirectionsRoutesObject <- jsonlite::fromJSON(DirectionsDirectionsRoutesJson)
      self$`legs` <- ApiClient$new()$deserializeObj(DirectionsDirectionsRoutesObject$`legs`, "array[object]", loadNamespace("openapi"))
      self$`weight_name` <- DirectionsDirectionsRoutesObject$`weight_name`
      self$`geometry` <- DirectionsDirectionsRoutesObject$`geometry`
      self$`weight` <- DirectionsDirectionsRoutesObject$`weight`
      self$`distance` <- DirectionsDirectionsRoutesObject$`distance`
      self$`duration` <- DirectionsDirectionsRoutesObject$`duration`
      self
    }
  )
)
