# LocationIQ
#
# LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
#
# The version of the OpenAPI document: 1.1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DirectionsNearest
#' @description DirectionsNearest Class
#' @format An \code{R6Class} generator object
#' @field code  character [optional]
#'
#' @field waypoints  list( \link{DirectionsNearestWaypoints} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DirectionsNearest <- R6::R6Class(
  'DirectionsNearest',
  public = list(
    `code` = NULL,
    `waypoints` = NULL,
    initialize = function(`code`=NULL, `waypoints`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`code`)) {
        stopifnot(is.character(`code`), length(`code`) == 1)
        self$`code` <- `code`
      }
      if (!is.null(`waypoints`)) {
        stopifnot(is.vector(`waypoints`), length(`waypoints`) != 0)
        sapply(`waypoints`, function(x) stopifnot(R6::is.R6(x)))
        self$`waypoints` <- `waypoints`
      }
    },
    toJSON = function() {
      DirectionsNearestObject <- list()
      if (!is.null(self$`code`)) {
        DirectionsNearestObject[['code']] <-
          self$`code`
      }
      if (!is.null(self$`waypoints`)) {
        DirectionsNearestObject[['waypoints']] <-
          lapply(self$`waypoints`, function(x) x$toJSON())
      }

      DirectionsNearestObject
    },
    fromJSON = function(DirectionsNearestJson) {
      DirectionsNearestObject <- jsonlite::fromJSON(DirectionsNearestJson)
      if (!is.null(DirectionsNearestObject$`code`)) {
        self$`code` <- DirectionsNearestObject$`code`
      }
      if (!is.null(DirectionsNearestObject$`waypoints`)) {
        self$`waypoints` <- ApiClient$new()$deserializeObj(DirectionsNearestObject$`waypoints`, "array[DirectionsNearestWaypoints]", loadNamespace("locationiq"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`code`)) {
        sprintf(
        '"code":
          "%s"
                ',
        self$`code`
        )},
        if (!is.null(self$`waypoints`)) {
        sprintf(
        '"waypoints":
        [%s]
',
        paste(sapply(self$`waypoints`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DirectionsNearestJson) {
      DirectionsNearestObject <- jsonlite::fromJSON(DirectionsNearestJson)
      self$`code` <- DirectionsNearestObject$`code`
      self$`waypoints` <- ApiClient$new()$deserializeObj(DirectionsNearestObject$`waypoints`, "array[DirectionsNearestWaypoints]", loadNamespace("locationiq"))
      self
    }
  )
)
