# LocationIQ
#
# LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
#
# OpenAPI spec version: 1.0.1
# 
# Generated by: https://openapi-generator.tech


#' Namedetails Class
#'
#' @field name 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Namedetails <- R6::R6Class(
  'Namedetails',
  public = list(
    `name` = NULL,
    initialize = function(`name`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      NamedetailsObject <- list()
      if (!is.null(self$`name`)) {
        NamedetailsObject[['name']] <- self$`name`
      }

      NamedetailsObject
    },
    fromJSON = function(NamedetailsJson) {
      NamedetailsObject <- jsonlite::fromJSON(NamedetailsJson)
      if (!is.null(NamedetailsObject$`name`)) {
        self$`name` <- NamedetailsObject$`name`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s
        }',
        self$`name`
      )
    },
    fromJSONString = function(NamedetailsJson) {
      NamedetailsObject <- jsonlite::fromJSON(NamedetailsJson)
      self$`name` <- NamedetailsObject$`name`
    }
  )
)
