# LocationIQ
#
# LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
#
# OpenAPI spec version: 1.0.1
# 
# Generated by: https://openapi-generator.tech

#' @title Search operations
#' @description locationiq.Search
#'
#' @field path Stores url path of the request.
#' @field apiClient Handles the client-server communication.
#'
#' @importFrom R6 R6Class
#'
#' @section Methods:
#' \describe{
#'
#' Search Forward Geocoding
#'
#' }
#'
#' @importFrom caTools base64encode
#' @export
SearchApi <- R6::R6Class(
  'SearchApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    Search = function(q, format, normalizecity, addressdetails=NULL, viewbox=NULL, bounded=NULL, limit=10, accept.language=NULL, countrycodes=NULL, namedetails=NULL, dedupe=NULL, extratags=NULL, statecode=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`q`)) {
        stop("Missing required parameter `q`.")
      }

      if (missing(`format`)) {
        stop("Missing required parameter `format`.")
      }

      if (missing(`normalizecity`)) {
        stop("Missing required parameter `normalizecity`.")
      }

      queryParams['q'] <- q

      queryParams['format'] <- format

      queryParams['normalizecity'] <- normalizecity

      queryParams['addressdetails'] <- addressdetails

      queryParams['viewbox'] <- viewbox

      queryParams['bounded'] <- bounded

      queryParams['limit'] <- limit

      queryParams['accept-language'] <- accept.language

      queryParams['countrycodes'] <- countrycodes

      queryParams['namedetails'] <- namedetails

      queryParams['dedupe'] <- dedupe

      queryParams['extratags'] <- extratags

      queryParams['statecode'] <- statecode

      urlPath <- "/search.php"
      # API key authentication
      if ("key" %in% names(self$apiClient$apiKeys) && nchar(self$apiClient$apiKeys["key"]) > 0) {
        queryParams['key'] <- paste(unlist(self$apiClient$apiKeys["key"]), collapse='')
      }

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        Location$new()$fromJSONString(httr::content(resp, "text", encoding = "UTF-8"))
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }

    }
  )
)
