# LocationIQ
#
# LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
#
# OpenAPI spec version: 1.0.1
# 
# Generated by: https://openapi-generator.tech

#' @title Search operations
#' @description locationiq.Search
#'
#' @field path Stores url path of the request.
#' @field apiClient Handles the client-server communication.
#' @field userAgent Set the user agent of the request.
#'
#' @importFrom R6 R6Class
#'
#' @section Methods:
#' \describe{
#'
#' search Forward Geocoding
#'
#' }
#'
#' @export
SearchApi <- R6::R6Class(
  'SearchApi',
  public = list(
    userAgent = "OpenAPI-Generator/1.0.0/r",
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    search = function(q, format, normalizecity, addressdetails, viewbox, bounded, limit, accept_language, countrycodes, namedetails, dedupe, extratags, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`q`)) {
        queryParams['q'] <- q
      }

      if (!missing(`format`)) {
        queryParams['format'] <- format
      }

      if (!missing(`normalizecity`)) {
        queryParams['normalizecity'] <- normalizecity
      }

      if (!missing(`addressdetails`)) {
        queryParams['addressdetails'] <- addressdetails
      }

      if (!missing(`viewbox`)) {
        queryParams['viewbox'] <- viewbox
      }

      if (!missing(`bounded`)) {
        queryParams['bounded'] <- bounded
      }

      if (!missing(`limit`)) {
        queryParams['limit'] <- limit
      }

      if (!missing(`accept_language`)) {
        queryParams['accept-language'] <- accept_language
      }

      if (!missing(`countrycodes`)) {
        queryParams['countrycodes'] <- countrycodes
      }

      if (!missing(`namedetails`)) {
        queryParams['namedetails'] <- namedetails
      }

      if (!missing(`dedupe`)) {
        queryParams['dedupe'] <- dedupe
      }

      if (!missing(`extratags`)) {
        queryParams['extratags'] <- extratags
      }

      urlPath <- "/search.php"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Location$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
  )
)
